---
  - name: make sure main resources dir exists
    file: path=../../build/resources/main state=directory

  - name: make sure test resources dir exists
    file: path=../../build/resources/test state=directory

  - name: make sure test resources dir exists
    file: path=../../build/env state=directory

  - name: replace host for test
    lineinfile: >
      dest=../../build/resources/test/env.properties.sample
      regexp=^orderingServiceHost=
      line=orderingServiceHost={{ hostvars['ordering-service'].ansible_ssh_host }}

  - name: replace port for test
    lineinfile: >
      dest=../../build/resources/test/env.properties.sample
      regexp=^orderingServicePort=
      line=orderingServicePort={{ hostvars['ordering-service'].ordering_service_port }}

  - name: make sure config file is ready
    copy: src=../../build/resources/test/env.properties.sample dest=../../build/resources/test/env.properties

  - name: replace flyway config
    template: src=flyway.properties dest=../../build/env/

  - name: replace datasource config
    template: src=hibernate.properties dest=../../build/env/

  - name: replace hibernate config
    template: src=datasource.properties dest=../../build/env/

#  - name: replace logback config
#    template: src=logback.xml dest=../../build/env/
